markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name:
url: http://caoanchay.com
description: Đơn giản chỉ là ghi và chép.
github: none
gravatar_url: none
