markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Cáo ăn chay
url: http://caoanchay.com
description: Đơn giản chỉ là ghi và chép.
twitter: none
github: none
gravatar_url: http://gravatar.com/avatar/6f63cde8b16b035280ca615f621a6c8c
