markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Cáo ăn chay
url: www.caoanchay.com
description: Đơn giản chỉ là ghi và chép.
github: none
gravatar_url: none


plugins:
  - jekyll-paginate
paginate: 8
paginate_path: /page-:num
